# =====================================================
# Handlers: Redis
# =====================================================

- name: "Reiniciar Redis"
  service:
    name: redis-server
    state: restarted
