<?php

declare(strict_types=1);

namespace Database\Factories;

use Domain\Ai\Models\AiKnowledgeChunk;
use Domain\Ai\Models\AiKnowledgeDocument;
use Domain\Platform\Models\PlatformTenant;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<AiKnowledgeChunk>
 */
class AiKnowledgeChunkFactory extends Factory
{
    protected $model = AiKnowledgeChunk::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $content = $this->generateChunkContent();

        return [
            'document_id' => AiKnowledgeDocument::factory(),
            'tenant_id' => \Domain\Platform\Models\PlatformTenant::query()->inRandomOrder()->first() ?? \Domain\Platform\Models\PlatformTenant::factory(),
            'chunk_index' => $this->faker->numberBetween(0, 100),
            'content' => $content,
            'token_count' => $this->faker->numberBetween(100, 500),
            'content_hash' => hash('sha256', $content),
            'embedding' => null, // Embeddings are generated by the service
            'created_at' => now(),
        ];
    }

    /**
     * Create for a specific document.
     */
    public function forDocument(AiKnowledgeDocument $document): static
    {
        return $this->state(fn (array $attributes): array => [
            'document_id' => $document->id,
            'tenant_id' => $document->tenant_id,
        ]);
    }

    /**
     * Create for a specific tenant.
     */
    public function forTenant(PlatformTenant $tenant): static
    {
        return $this->state(fn (array $attributes): array => [
            'tenant_id' => $tenant->id,
        ]);
    }

    /**
     * Set a specific chunk index.
     */
    public function atIndex(int $index): static
    {
        return $this->state(fn (array $attributes): array => [
            'chunk_index' => $index,
        ]);
    }

    /**
     * Set specific content.
     */
    public function withContent(string $content): static
    {
        return $this->state(fn (array $attributes): array => [
            'content' => $content,
            'token_count' => $this->estimateTokenCount($content),
        ]);
    }

    /**
     * Set specific token count.
     */
    public function withTokenCount(int $tokenCount): static
    {
        return $this->state(fn (array $attributes): array => [
            'token_count' => $tokenCount,
        ]);
    }

    /**
     * Set with a mock embedding (random 1536-dimension vector).
     */
    public function withEmbedding(): static
    {
        return $this->state(fn (array $attributes): array => [
            'embedding' => $this->generateMockEmbedding(),
        ]);
    }

    /**
     * Generate realistic chunk content.
     */
    private function generateChunkContent(): string
    {
        $paragraphs = $this->faker->paragraphs($this->faker->numberBetween(2, 4));

        return implode("\n\n", $paragraphs);
    }

    /**
     * Estimate token count for content (rough approximation).
     */
    private function estimateTokenCount(string $content): int
    {
        // Rough estimate: ~4 characters per token
        return (int) ceil(mb_strlen($content) / 4);
    }

    /**
     * Generate a mock 1536-dimension embedding vector.
     *
     * @return list<float>
     */
    private function generateMockEmbedding(): array
    {
        $embedding = [];
        for ($i = 0; $i < 1536; $i++) {
            $embedding[] = $this->faker->randomFloat(8, -1, 1);
        }

        // Normalize the vector
        $magnitude = sqrt(array_sum(array_map(fn ($x): float => $x * $x, $embedding)));
        if ($magnitude > 0) {
            return array_map(fn ($x): float => $x / $magnitude, $embedding);
        }

        return $embedding;
    }
}
