# =====================================================
# Handlers: PHP
# =====================================================

- name: "Reiniciar PHP-FPM"
  service:
    name: php8.4-fpm
    state: restarted
